apiVersion: v1
kind: Service
metadata:
  namespace: entity
  name: entity-service
spec:
  selector:
    app: entity-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
