apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: micro-service-101
  name: micro-service-101
spec:
  replicas: 3
  template:
    spec:
      serviceAccountName: micro-service-101-sa
      containers:
        - name: micro-service-101
          image: docker.io/muk007/spring-boot:version-18
      imagePullSecrets:
        - name: my-dockerhub-secret
