apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: micro-service-101
  namespace: micro-service-101
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/v1/say-hello
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/v1/say-hello
            pathType: Prefix
            backend:
              service:
                name: micro-service-101
                port:
                  number: 8080
