datadog:
  apiKey: 159a1b024973d01f954bde952a7c78f1
  site: datadoghq.com 
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    enabled: true
  
  clusterAgent:
    enabled: true
  tags: 
    - "env:sandbox"
    - "team:devops"
  
