apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: entity
  name: entity-service
spec:
  replicas: 3
  template:
    spec:
      serviceAccountName: entity-sa
      containers:
        - name: entity-service
          image: docker.io/muk007/nginx:version-97
      imagePullSecrets:
        - name: my-dockerhub-secret
