apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: entity
  name: entity-service
spec:
  replicas: 3
  template:
    spec:
      serviceaccount: entity-sa
      containers:
        - name: entity-service
          image: nginx:alpine
