apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: generalledger
  name: gl-service
  labels:
    app: gl-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gl-service
  template:
    metadata:
      labels:
        app: gl-service
    spec:
      containers:
        - name: gl-service
          image: nginx:latest
          ports:
            - containerPort: 80
