apiVersion: v1
kind: Service
metadata:
  namespace: generalledger
  name: gl-service
spec:
  selector:
    app: gl-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
