apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-components
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: ingress-controller-components
            namespace: ingress-nginx
            path: core/ingress-controller
  template:
    metadata:
      name: "{{name}}"
      namespace: argocd
    spec:
      project: core-components
      source:
        repoURL: https://github.com/devops-contribution/k8s-apps
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

