apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: accounts
  name: account-service
  labels:
    app: account-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: tomcat:latest
          ports:
            - containerPort: 8080
