apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: accounts
  name: account-service
spec:
  replicas: 4
  template:
    spec:
      containers:
        - name: account-service
          image: tomcat:latest
